services:
  server:
    container_name: et_server
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: sh -c "pnpm prisma db push && pnpm dev"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app

  client:
    container_name: et_client
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    command: pnpm dev
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app

  mysql:
    container_name: et_mysql
    image: mysql:8.4.2
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    env_file:
      - .env
    healthcheck:
      test: [ CMD, mysqladmin, ping, --silent ]
      interval: 1m30s
      timeout: 30s
      start_period: 30s
      retries: 5
    networks:
      - app

  phpmyadmin:
    container_name: et_phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PMA_HOST=mysql
    env_file:
      - .env
    networks:
      - app

volumes:
  db_data:


networks:
  app:
    driver: bridge
