services:
 server:
  build: ./server
  volumes:
   - ./server:/usr/src/app
   - /usr/src/app/node_modules
  ports:
   - 3000:3000
  environment:
   - PORT=3000
  depends_on:
   mysql:
    condition: service_healthy
  networks:
   - app
  command: pnpm dev

 client:
  build: ./client
  volumes:
   - ./client:/usr/src/app
   - /usr/src/app/node_modules
  ports:
   - 5174:5174
  environment:
   - PORT=5174
  depends_on:
   mysql:
    condition: service_healthy
  networks:
   - app
  command: pnpm dev

 mysql:
  image: mysql:8.4.2
  restart: always
  ports:
   - 3306:3306
  volumes:
   - db_data:/var/lib/mysql
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=true
  healthcheck:
   test: [ CMD, mysqladmin, ping, --silent ]
   interval: 5s
   timeout: 5s
   start_period: 30s
   retries: 5
  networks:
   - app

 phpmyadmin:
  image: phpmyadmin:5.2.1
  restart: always
  ports:
   - 80:80
  depends_on:
   mysql:
    condition: service_healthy
  environment:
   - PMA_HOST=mysql
  networks:
   - app

volumes:
 db_data:


networks:
 app:
  driver: bridge
